In [ ]:
Creation of ndarray

1.Write python code to create 3d array in different ways with 15 elements.
2.Array Creation:
    
a. Create a 4D NumPy array containing the first 12 positive integers as arr1. 
b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1. 

3. Find all attributes of array1 and array2 
4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

Array Slicing and Indexing:

a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29]. 
- Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].
b.Basic Indexing: - Print the element at index 3 of arr1. 
- Print the element at row 2, column 1 of arr2
c. Array Slicing: - Print the first five elements of arr1. 
- Print the subarray of arr2 consisting of the last two rows and the first two columns. 
- Print every second element starting from index 1 up to index 7 of arr1.

Data Type Manipulation
a. Creating Arrays with Specific Data Types: 
    - Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. 
    - Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.
b. Data Type Conversion: - Convert the float_array to an array with data type int32. Print the result. 
    - Convert the int_array to an array with data type float32. Print the result.

Generating Random Numbers:

Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).
Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.
Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix
Apply descriptive statistics for rand_matrix.

Analyze the Data:
Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following:
1.How many employees are getting more less than 50000?
2.Is it following Normal Distribution?
3.What is the median salary?
4.What is the range of salaries for this company?
5.Find the salaries between average salary and 75% of salaries?
6.How many employees are getting less than 25 % of salaries ?

 

### creation

#### 1.Write python code to create 3d array in different ways with 15 elements.

In [2]:
import numpy as np

In [5]:
#using ndimn
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15],ndmin=3)
arr1

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [6]:
arr1.ndim

3

In [7]:
#using square bracket
arr2 = np.array([[[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]]])
arr2

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]]])

In [8]:
arr2.ndim

3

In [11]:
arr3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]).reshape(3,1,5)
arr3

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15]]])

In [12]:
arr3.ndim

3

In [15]:
arr4 = np.arange(1,16,1).reshape(5,1,3)
arr4

array([[[ 1,  2,  3]],

       [[ 4,  5,  6]],

       [[ 7,  8,  9]],

       [[10, 11, 12]],

       [[13, 14, 15]]])

In [16]:
arr4.ndim

3

### 2.Array Creation:

#### a. Create a 4D NumPy array containing the first 12 positive integers as arr1. 

In [5]:
arr1 = np.arange(1,13,1).reshape(2,3,1,2)
arr1

array([[[[ 1,  2]],

        [[ 3,  4]],

        [[ 5,  6]]],


       [[[ 7,  8]],

        [[ 9, 10]],

        [[11, 12]]]])

In [19]:
arr1.ndim

4

#### b. Create a 3D NumPy array1 with 20 random elements containing integers between 0 and 1. 

In [4]:
array1 = np.random.randint(0,2,20)
array1

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0])

#### 3. Find all attributes of array1 and array2 

##### arr1

In [6]:
arr1

array([[[[ 1,  2]],

        [[ 3,  4]],

        [[ 5,  6]]],


       [[[ 7,  8]],

        [[ 9, 10]],

        [[11, 12]]]])

In [7]:
arr1.ndim

4

In [8]:
arr1.nbytes

48

In [9]:
arr1.dtype

dtype('int32')

In [10]:
arr1.itemsize

4

In [11]:
arr1.size

12

##### array2

In [13]:
array2 = np.random.rand(5,1,4)
array2

array([[[0.48407378, 0.86967777, 0.35148575, 0.30731778]],

       [[0.56466842, 0.64486819, 0.66723876, 0.18284985]],

       [[0.14159526, 0.89530717, 0.13750915, 0.37828046]],

       [[0.3523657 , 0.91566425, 0.24185047, 0.98682537]],

       [[0.1037163 , 0.80027033, 0.64879701, 0.98770743]]])

In [14]:
array2.ndim

3

In [15]:
array2.dtype

dtype('float64')

In [16]:
array2.nbytes

160

In [17]:
array2.size

20

In [18]:
array2.itemsize

8

#### 4. Apply measure and describe the data (attributes and descriptive statistics) to above arrays using NumPy.

##### arr1

**Describe**
* structure(rowsxcolumns) : 6x2
* datatype : int32
* outliers : 0
* Missing values : 0

#### Measure of central tendency

In [19]:
#mean
np.mean(arr1)

6.5

In [20]:
#median
np.median(arr1)

6.5

#### Measure of spread

In [21]:
#range
#max
np.max(arr1)

12

In [22]:
#min
np.min(arr1)

1

In [23]:
range = np.max(arr1)-np.min(arr1)
range

11

In [24]:
#IQR
#q1
q1 = np.percentile(arr1,25)
q1

3.75

In [26]:
#q3
q3 = np.percentile(arr1,75)
q3

9.25

In [27]:
#IQR
IQR = q3-q1
IQR

5.5

In [28]:
lower = q1-(1.5*IQR)
lower

-4.5

In [29]:
upper = q3+(1.5*IQR)
upper

17.5

In [34]:
#outliers
print(arr1[arr1>upper])
print(arr1[arr1<lower])   #no outliers

[]
[]


In [31]:
#variance
np.var(arr1)

11.916666666666666

In [32]:
#standard deviation
np.std(arr1)

3.452052529534663

##### array2

In [35]:
array2

array([[[0.48407378, 0.86967777, 0.35148575, 0.30731778]],

       [[0.56466842, 0.64486819, 0.66723876, 0.18284985]],

       [[0.14159526, 0.89530717, 0.13750915, 0.37828046]],

       [[0.3523657 , 0.91566425, 0.24185047, 0.98682537]],

       [[0.1037163 , 0.80027033, 0.64879701, 0.98770743]]])

**Describe**
* structure(rowsxcolumns) : 5x4
* datatype : float64
* missing values : 0
* outliers : 0

#### Measure of central tendency

In [36]:
#mean
np.mean(array2)

0.533103459754662

In [37]:
np.median(array2)

0.5243710960168495

#### Measure of spread

In [38]:
#range
#max
np.max(array2)

0.9877074346090767

In [39]:
#min
np.min(array2)

0.10371629707654983

In [40]:
range = np.max(array2)-np.min(array2)
range

0.8839911375325269

In [41]:
#IQR
#q1
q1 = np.percentile(array2,25)
q1

0.2909509511779257

In [42]:
#q3
q3 = np.percentile(array2,75)
q3

0.817622188012626

In [43]:
IQR = q3-q1
IQR

0.5266712368347003

In [44]:
lower = q1-(1.5*IQR)
lower

-0.4990559040741248

In [45]:
upper = q3+(1.5*IQR)
upper

1.6076290432646765

In [47]:
#outliers
print(array2[array2>upper]) #no outliers
print(array2[array2<lower])

[]
[]


In [48]:
#variance
np.var(array2)

0.08821275756382428

In [49]:
#standard deviation
np.std(array2)

0.2970063257976575

### Array Slicing and Indexing:

In [ ]:
a. Creating Arrays: - Create a 1-dimensional NumPy array arr1 with the values [0, 11, 26, 73, 42, 51, 6,77, 8,29].
Create a 2-dimensional NumPy array arr2 with the values [[0, 1, 2], [3, 4, 5], [6, 7, 8]].

In [50]:
arr1 = np.array([0, 11, 26, 73, 42, 51, 6,77, 8,29])
arr1

array([ 0, 11, 26, 73, 42, 51,  6, 77,  8, 29])

In [51]:
arr1.ndim

1

In [52]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
arr2.ndim

2

#### b.Basic Indexing: - Print the element at index 3 of arr1. 

In [54]:
arr1[3]

73

#### Print the element at row 2, column 1 of arr2

In [55]:
arr2[2][1]

7

### c. Array Slicing: 

##### Print the first five elements of arr1. 

In [57]:
arr1[:5]

array([ 0, 11, 26, 73, 42])

##### Print the subarray of arr2 consisting of the last two rows and the first two columns. 

In [58]:
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
arr2[1:3,0:2]

array([[3, 4],
       [6, 7]])

##### Print every second element starting from index 1 up to index 7 of arr1.

In [71]:
arr1[1:7:2]

array([11, 73, 51])

### Data Type Manipulation

##### a.Creating Arrays with Specific Data Types: 
##### Create a 1-dimensional NumPy array int_array with the values [1, 2, 3, 4, 5] and the data type int16. 

In [72]:
int_array = np.array([1, 2, 3, 4, 5],dtype = 'int16') #in the output you can observe the dtype or you can check it again
int_array

array([1, 2, 3, 4, 5], dtype=int16)

In [73]:
int_array.dtype

dtype('int16')

##### Create a 1-dimensional NumPy array float_array with the values [0.1, 0.2, 0.3, 0.4, 0.5] and the data type float64.

In [75]:
float_array = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
float_array

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [76]:
float_array.dtype  #no need to mention float64, by default it considers float64 only

dtype('float64')

### b. Data Type Conversion: 

##### Convert the float_array to an array with data type int32. Print the result. 

In [79]:
a = np.array(float_array,dtype = 'int32')
a

array([0, 0, 0, 0, 0])

In [80]:
a.dtype

dtype('int32')

##### Convert the int_array to an array with data type float32. Print the result.

In [81]:
b = np.array(int_array,dtype = 'float32')
b

array([1., 2., 3., 4., 5.], dtype=float32)

In [82]:
b.dtype

dtype('float32')

### Generating Random Numbers:

##### Use numpy.random.randint() to create an array rand_integers containing 10 random integers between 0 and 100 (inclusive).

In [85]:
rand_integers = np.random.randint(0,101,10)
rand_integers

array([ 5, 48, 82, 69,  6, 46, 15, 65, 35, 30])

##### Use numpy.random.uniform() to create an array rand_uniform containing 5 random numbers sampled from a uniform distribution between -1 and 1.

In [86]:
rand_uniform = np.random.uniform(-1,1,5)
rand_uniform

array([-0.75939709, -0.09557746, -0.47029417, -0.58718362, -0.52315136])

##### Create an array rand_matrix with random integers between 50 and 100 (inclusive).and reshape it to 2-dimensional (4 x 4) matrix

In [88]:
rand_matrix = np.random.randint(50,101,16).reshape(4,4)
rand_matrix

array([[55, 89, 90, 97],
       [76, 65, 68, 84],
       [71, 56, 99, 79],
       [80, 98, 78, 89]])

##### Apply descriptive statistics for rand_matrix.

###### Measure of central tendency

In [89]:
#mean
np.mean(rand_matrix)

79.625

In [90]:
#median
np.median(rand_matrix)

79.5

###### Measure of spread

In [91]:
#range
#max
np.max(rand_matrix)

99

In [92]:
#min
np.min(rand_matrix)

55

In [93]:
range = np.max(rand_matrix)-np.min(rand_matrix)
range

44

In [94]:
#IQR
#q1
q1 = np.percentile(rand_matrix,25)
q1

70.25

In [95]:
#q3
q3 = np.percentile(rand_matrix,75)
q3

89.25

In [96]:
IQR = q3-q1
IQR

19.0

In [97]:
lower = q1-(1.5*IQR)
lower

41.75

In [98]:
upper = q3+(1.5*IQR)
IQR

19.0

In [100]:
print(rand_matrix[rand_matrix<lower])   #no outliers
print(rand_matrix[rand_matrix>upper])

[]
[]


In [101]:
#variance
np.var(rand_matrix)

182.609375

In [102]:
#standard deviation
np.std(rand_matrix)

13.513303630126869

In [ ]:
Analyze the Data:
Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

Describe the data using numpy array. Measure the following:
1.How many employees are getting more less than 50000?
2.Is it following Normal Distribution?
3.What is the median salary?
4.What is the range of salaries for this company?
5.Find the salaries between average salary and 75% of salaries?
6.How many employees are getting less than 25 % of salaries ?


In [105]:
Salaries = [87877, 54494, 54804, 85051, 52453, 31250, 94868, 66349, 39828, 60501, 58570, 74906, 41671, 51428, 56414, 98446, 56819, 82833, 50477, 62898, 99658, 89224, 34225, 79172, 32199, 63795, 90947, 55723, 64557, 3113638]

In [106]:
sal = np.array(Salaries)
sal

array([  87877,   54494,   54804,   85051,   52453,   31250,   94868,
         66349,   39828,   60501,   58570,   74906,   41671,   51428,
         56414,   98446,   56819,   82833,   50477,   62898,   99658,
         89224,   34225,   79172,   32199,   63795,   90947,   55723,
         64557, 3113638])

##### 1.How many employees are getting more less than 50000?

In [112]:
len(sal[sal<50000])

5

##### 2.Is it following Normal Distribution?

In [ ]:
no

##### 3.What is the median salary?

In [114]:
np.median(sal)

61699.5

##### 4.What is the range of salaries for this company?

In [116]:
range = np.max(sal)-np.min(sal)
range

3082388

##### 5.Find the salaries between average salary and 75% of salaries?

In [119]:
q3 = np.percentile(sal,75)
print(q3)
m = np.mean(sal)
print(m)

84496.5
166169.16666666666


In [121]:
between = sal[(sal>m) & (sal<q3)]
between

array([], dtype=int32)

##### 6.How many employees are getting less than 25 % of salaries ?

In [124]:
q1 = np.percentile(sal,25)
len(sal[sal<q1])

8