In [ ]:

Data Cleaning using numpy
The following are the student marks of a class [44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]

Find the no of outliers and missing values?
replace the outliers with 45 and missing value with 87.
what is the average marks of students after 2nd step?
How many students got less than 60 marks?
what is the maximum marks?
Convert the marks to float32.
Solving Linear Equations
2x + 3y - z = 10
x - y + 2z = 5
3x + 2y + z = 12

2x + y - z + 3w = 8
3x - 2y + 2z + 2w = 1
x + 3y - 2z + w = 7
4x - y + z - 2w = 3

4x + 2y - 3z = 10
-2x + 3y + z = -3
x - y + 2z = 4

Solve the system of equations using NumPy's linalg.solve function.

Conditional Selection with np.where()
Generate a random 1D array A of 10 integers between 1 and 100.

Use np.where() to find the indices where the elements of A are greater than 50.

Create a new array B that contains elements from A where the condition is met.

Calculate the mean of array B and print it along with arrays A and B.

Replace Values with np.where()
Create a 4x4 random integer matrix C with values between -10 and 10.

Use np.where() to replace all negative values in matrix C with 0.

Print the original matrix C and the modified matrix.

 

In [ ]:
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53, 44]

#### Find the no of outliers and missing values?

In [13]:
import numpy as np

In [21]:
marks = np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53,44])

In [22]:
marks

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  44.])

In [15]:
missingvalues = np.sum(np.isnan(marks))
missingvalues   #no.of missing values

4

In [16]:
cond = (marks>100)|(marks<0)
cond

array([False, False, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [17]:
np.sum(cond)  #no.of outliers

3

In [23]:
marks1 = np.where(np.isnan(marks),45,marks).astype('int16')
marks1 

array([ 44,  24,  45,  59,  32,  96, 188,  52,  62,  58,  52, 120,  45,
        45,   3,  56,  81,  59, 122,  92,  45,  87,  96,  97,   1,  19,
         2,  53,  44], dtype=int16)

In [24]:
marks2 = np.where(cond,87,marks1)
marks2

array([44, 24, 45, 59, 32, 96, 87, 52, 62, 58, 52, 87, 45, 45,  3, 56, 81,
       59, 87, 92, 45, 87, 96, 97,  1, 19,  2, 53, 44], dtype=int16)

In [36]:
marks2

array([44, 24, 45, 59, 32, 96, 87, 52, 62, 58, 52, 87, 45, 45,  3, 56, 81,
       59, 87, 92, 45, 87, 96, 97,  1, 19,  2, 53, 44], dtype=int16)

#### what is the average marks of students after 2nd step?

In [26]:
np.mean(marks2)  #average

55.51724137931034

In [27]:
np.average(marks2)

55.51724137931034

In [79]:
np.mean(marks1)

61.3448275862069

#### How many students got less than 60 marks?

In [33]:
np.sum(marks2<60)

19

In [34]:
len(marks2[marks2<60])

19

#### what is the maximum marks?

In [37]:
np.max(marks2)

97

#### Convert the marks to float32.

In [39]:
np.array(marks2.astype('float32'))

array([44., 24., 45., 59., 32., 96., 87., 52., 62., 58., 52., 87., 45.,
       45.,  3., 56., 81., 59., 87., 92., 45., 87., 96., 97.,  1., 19.,
        2., 53., 44.], dtype=float32)

### Solve the system of equations using NumPy's linalg.solve function.

In [ ]:
2x + 3y - z = 10
x - y + 2z = 5
3x + 2y + z = 12

In [40]:
a = np.array([[2,3,-1],[1,-1,2],[3,2,1]])
a

array([[ 2,  3, -1],
       [ 1, -1,  2],
       [ 3,  2,  1]])

In [42]:
b = np.array([10,5,12])
b

array([10,  5, 12])

In [43]:
np.linalg.solve(a,b)

array([-6.75539944e+15,  6.75539944e+15,  6.75539944e+15])

In [ ]:
2x + y - z + 3w = 8
3x - 2y + 2z + 2w = 1
x + 3y - 2z + w = 7
4x - y + z - 2w = 3

In [44]:
c = np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
c

array([[ 2,  1, -1,  3],
       [ 3, -2,  2,  2],
       [ 1,  3, -2,  1],
       [ 4, -1,  1, -2]])

In [45]:
d = np.array([8,1,7,3])
d

array([8, 1, 7, 3])

In [46]:
np.linalg.solve(c,d)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

In [ ]:
4x + 2y - 3z = 10
-2x + 3y + z = -3
x - y + 2z = 4

In [47]:
e = np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
e

array([[ 4,  2, -3],
       [-2,  3,  1],
       [ 1, -1,  2]])

In [48]:
f = np.array([10,-3,4])
f

array([10, -3,  4])

### Conditional Selection with np.where()

#### Generate a random 1D array A of 10 integers between 1 and 100.

In [49]:
A = np.random.randint(1,100,10)
A

array([24, 15, 48, 26, 50,  7, 59, 74, 77, 73])

#### Use np.where() to find the indices where the elements of A are greater than 50.

In [50]:
np.where(A>50)

(array([6, 7, 8, 9], dtype=int64),)

#### Create a new array B that contains elements from A where the condition is met.

In [57]:
B = np.array(A[A>50])
B

array([59, 74, 77, 73])

#### Calculate the mean of array B and print it along with arrays A and B.

In [58]:
np.mean(B)

70.75

In [59]:
np.mean(A)

45.3

### Replace Values with np.where()

#### Create a 4x4 random integer matrix C with values between -10 and 10.

In [74]:
c = np.random.randint(-10,10,16).reshape(4,4)
c

array([[-5,  9, -6,  0],
       [ 5, -6, -2,  6],
       [-1,  7, -6, -2],
       [ 7,  4,  4,  4]])

#### Use np.where() to replace all negative values in matrix C with 0.

In [75]:
d = np.where(c<0,0,c)
d

array([[0, 9, 0, 0],
       [5, 0, 0, 6],
       [0, 7, 0, 0],
       [7, 4, 4, 4]])

#### Print the original matrix C and the modified matrix.

In [77]:
c

array([[-5,  9, -6,  0],
       [ 5, -6, -2,  6],
       [-1,  7, -6, -2],
       [ 7,  4,  4,  4]])

In [78]:
d

array([[0, 9, 0, 0],
       [5, 0, 0, 6],
       [0, 7, 0, 0],
       [7, 4, 4, 4]])